<?php

// Set class property
require_once dirname(__FILE__) . "/functions.php";

scs_ytap_main();

function scs_ytap_main()
{
    $options = get_option('scs_ytap_options');
    $scs_apikey = $options['apikey'];
    $scs_channelId = $options['channelId'];
    $scs_noofvids = $options['noofvids'];
    $scs_post_status = $options['post_status'];
    $scs_post_category = $options['post_category'];
    $scs_post_author = $options['post_author'];
    $scs_post_date = $options['post_date'];
    $scs_ytap_shortcodes = $options['scs_ytap_shortcodes'];
    $scs_publishedAfter = $options['publishedAfter'];
    $scs_publishedBefore = $options['publishedBefore'];
    $scs_cronDay = $options['cronDay'];

    if (isset($options['scs_ytap_shortcodes'])) {
        $scs_ytap_shortcodes = $options['scs_ytap_shortcodes'];} else { $scs_ytap_shortcodes = "";}
    if (strpos($scs_ytap_shortcodes, '[scs_ytap_video-captions]') == false) {
        $autogencaptionsswitch = false;
    } else { $autogencaptionsswitch = true;}

    $scs_ytap_output_result = "";
    $allwpytids = scs_ytap_getYtIdsFromPosts();
    $data = scs_ytap_getYtVideoListData($scs_apikey, $scs_channelId, $scs_noofvids, $scs_publishedAfter, $scs_publishedBefore);

    for ($j = 0; $j < $scs_noofvids; $j++) {

        $currvidid = $data['items'][$j]['id']['videoId'];
        $currvidtitle = $data['items'][$j]['snippet']['title'];
        $scs_yt_post_date = $data['items'][$j]['snippet']['publishedAt'];
        $vidno = $j + 1;

        //first we check if post was already created in wordpress by video id
        if (!in_array($currvidid, $allwpytids)) {

            $viddata = scs_ytap_getYtVideoIndividualData($scs_apikey, $currvidid);
            $currviddes = $viddata['items'][0]['snippet']['description'];
            if (!isset($currviddes)) {$currviddes = "";}
            $curthumb = $viddata['items'][0]['snippet']['thumbnails']['high']['url'];
            $currvidcatid = $viddata['items'][0]['snippet']['categoryId'];
            if (isset($viddata['items'][0]['snippet']['tags'])) {$currvidtags = $viddata['items'][0]['snippet']['tags'];} else { $currvidtags = ["yt", "youtube"];}        
            //then we get the autogenerated captions
            if ($autogencaptionsswitch) {$autogencaptions = scs_ytap_getClosedCaptionsForVideo($currvidid);} else { $autogencaptions = "";}
            scs_ytap_createPost($currvidtitle, $scs_post_status, $currvidid, $currviddes, $autogencaptions, $currvidtags, $curthumb, $scs_ytap_shortcodes, $scs_post_category, $scs_post_author, $scs_post_date, $scs_yt_post_date);

        }

    }

}
