<?php

// Set class property
require_once dirname(__FILE__) . "/functions.php";

scs_ytap_main();

function scs_ytap_main()
{
    global $scs_apikey;
    global $scs_channelId;
    global $scs_noofvids;
    global $scs_post_status;
    global $scs_ytap_shortcodes;
    global $scs_publishedAfter;
    global $scs_publishedBefore;
    global $scs_post_category;
    global $scs_post_author;
    global $scs_post_date;
    global $autogencaptionsswitch;
    global $scs_ytap_output_result;

    global $wpdb;
    global $options;
    $options = get_option('scs_ytap_options');
    $scs_apikey = $options['apikey'];
    $scs_channelId = $options['channelId'];
    $scs_noofvids = $options['noofvids'];
    $scs_post_status = $options['post_status'];
    $scs_post_category = $options['post_category'];
    $scs_post_author = $options['post_author'];
    $scs_post_date = $options['post_date'];
    $scs_ytap_shortcodes = $options['scs_ytap_shortcodes'];
    $scs_publishedAfter = $options['publishedAfter'];
    $scs_publishedBefore = $options['publishedBefore'];
    $scs_cronDay = $options['cronDay'];
   

    $scs_ytap_output_result = "";
    $allwpytids = scs_ytap_getYtIdsFromPosts();

    $data = scs_ytap_getYtVideoListData($scs_apikey, $scs_channelId, $scs_noofvids, $scs_publishedAfter, $scs_publishedBefore);

    for ($j = 0; $j < $scs_noofvids; $j++) {

        $currvidid = $data['items'][$j]['id']['videoId'];
        $currvidtitle = $data['items'][$j]['snippet']['title'];
        $scs_yt_post_date = $data['items'][$j]['snippet']['publishedAt'];
        $vidno = $j + 1;

        //first we check if post was already created in wordpress by video id
        if (!in_array($currvidid, $allwpytids)) {
            $scs_ytap_output_result .= "<div class='scsposted'><b>Video $vidno:</b> $currvidtitle <i>[$currvidid]</i> posted!</div>";

            $viddata = scs_ytap_getYtVideoIndividualData($scs_apikey, $currvidid);

            $currviddes = $viddata['items'][0]['snippet']['description'];

            if (!isset($currviddes)) {$currviddes = "";}

            $curthumb = $viddata['items'][0]['snippet']['thumbnails']['high']['url'];

            $currvidcatid = $viddata['items'][0]['snippet']['categoryId'];

            if (isset($viddata['items'][0]['snippet']['tags'])) {$currvidtags = $viddata['items'][0]['snippet']['tags'];} else { $currvidtags = ["yt", "youtube"];}
            //echo "TAGS: " . $currvidtags . "<br>";

            for ($i = 0; $i < count($currvidtags); $i++) {
                // echo $currvidtags[$i] . ", ";
            }
            //then we get the autogenerated captions
            if ($autogencaptionsswitch) {$autogencaptions = getClosedCaptionsForVideo($currvidid);} else { $autogencaptions = "";}

            scs_ytap_createPost($currvidtitle, $scs_post_status, $currvidid, $currviddes, $autogencaptions, $currvidtags, $curthumb, $scs_ytap_shortcodes, $scs_post_category, $scs_post_author, $scs_post_date, $scs_yt_post_date);

        } else { $scs_ytap_output_result .= "<div class='scsalreadyposted'><b>Video $vidno:</b> $currvidtitle <i>[$currvidid]</i> already posted!</div>";}

    }

    echo "<div class='scsemulatetextarea'><b>Output log:</b><br>" . $scs_ytap_output_result . "</div>";

}
