<?php
/**
 * Plugin Name:       SCS YouTube Auto Poster
 * Description:       Auto Posts newest YouTube videos from the Youtube channel(s) of your choice.
 * Version:           2018.11.23
 * Author:            Mike Mind
 * Author URI:        https://mikemind.me
 * Text Domain:       mikemind.me
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * GitHub Plugin URI: https://github.com/
 */

//here we make the settings menu
class MySettingsPage
{
    /**
     * Holds the values to be used in the fields callbacks
     */
    private $options;

    /**
     * Start up
     */
    public function __construct()
    {
        add_action('admin_menu', array($this, 'add_plugin_page'));
        add_action('admin_init', array($this, 'page_init'));
    }

    /**
     * Add options page
     */
    public function add_plugin_page()
    {
        // This page will be under "Settings"
        add_options_page(
            'SCS Auto Poster Options',
            'SCS Auto Poster',
            'manage_options',
            'scs_ytap',
            // array( $this, 'create_admin_page' )
            array($this, 'tytttap')
        );
    }

    /**
     * Options page callback
     */
    public function create_admin_page()
    {
        // Set class property
        //   $this->options = get_option( 'my_option_name' );

        ?>
        <div class="wrap">
            <h1>My Settings</h1>
            <form method="post" action="options.php">
            <?php
// This prints out all hidden setting fields
        //    settings_fields( 'my_option_group' );
        //    do_settings_sections( 'my-setting-admin' );

        //submit_button();
        ?>
            </form>
        </div>
        <?php
}

    /**
     * Register and add settings
     */
    public function page_init()
    {
        //echo "myyy settings";
    }

    public function tytttap()
    {
        include dirname(__FILE__) . "/functions.php";

        echo "<h1>POSTS CREATED! ...</h1>";

        $allwpytids = scs_ytap_getYtIdsFromPosts();

        $data = scs_ytap_getYtVideoListData($scs_apikey, $scs_channelId, $scs_noofvids);
        //echo $data;

        for ($j = 0; $j < $scs_noofvids; $j++) {
            echo "<br><h2>Video $j:</h2>";
            $currvidid = $data['items'][$j]['id']['videoId'];
            $currvidtitle = $data['items'][$j]['snippet']['title'];

            //first we check if post was already created in wordpress by video id
            if (!in_array($currvidid, $allwpytids)) {

                $viddata = scs_ytap_getYtVideoIndividualData($scs_apikey, $currvidid);

                echo "ID: " . $currvidid . "<br>";
                $currviddes = $viddata['items'][0]['snippet']['description'];
                //echo "DESCRIPTION: " . $currviddes . "<br>";
                $curthumb = $viddata['items'][0]['snippet']['thumbnails']['high']['url'];
                //echo "THUMBNAIL: " . $curthumb . "<br>";
                //todo category id and matches category from site
                $currvidcatid = $viddata['items'][0]['snippet']['categoryId'];
                //echo "CATEGORY ID: " . $currvidcatid . "<br>";
                $currvidtags = $viddata['items'][0]['snippet']['tags'];
                //echo "TAGS: " . $currvidtags . "<br>";

                for ($i = 0; $i < count($currvidtags); $i++) {
                    // echo $currvidtags[$i] . ", ";
                }
                //then we get the autogenerated captions
                $autogencaptions = getClosedCaptionsForVideo($currvidid);

                scs_ytap_createPost($currvidtitle,$scs_post_status,$currvidid,$currviddes,$autogencaptions,$currvidtags,$curthumb);

            } else {echo "Video '" . $currvidtitle . "' already posted! <br>";}

        }

    }

}

if (is_admin()) {
    $my_settings_page = new MySettingsPage();
}
